(cl:in-package kortex_driver-msg)
(cl:export '(SEQUENCE_HANDLE-VAL
          SEQUENCE_HANDLE
          ACTION_HANDLE-VAL
          ACTION_HANDLE
          MAPPING_HANDLE-VAL
          MAPPING_HANDLE
          MAP_GROUP_HANDLE-VAL
          MAP_GROUP_HANDLE
          MAP_HANDLE-VAL
          MAP_HANDLE
          USER_PROFILE_HANDLE-VAL
          USER_PROFILE_HANDLE
          PROTECTION_ZONE_HANDLE-VAL
          PROTECTION_ZONE_HANDLE
          SAFETY_HANDLE-VAL
          SAFETY_HANDLE
          NETWORK_HANDLE-VAL
          NETWORK_HANDLE
          SSID-VAL
          SSID
          CONTROLLER_HANDLE-VAL
          CONTROLLER_HANDLE
))