(cl:in-package kortex_driver-msg)
(cl:export '(COMMAND_ID-VAL
          COMMAND_ID
          STATUS_FLAGS-VAL
          STATUS_FLAGS
          JITTER_COMM-VAL
          JITTER_COMM
          POSITION-VAL
          POSITION
          VELOCITY-VAL
          VELOCITY
          TORQUE-VAL
          TORQUE
          CURRENT_MOTOR-VAL
          CURRENT_MOTOR
          VOLTAGE-VAL
          VOLTAGE
          TEMPERATURE_MOTOR-VAL
          TEMPERATURE_MOTOR
          TEMPERATURE_CORE-VAL
          TEMPERATURE_CORE
          FAULT_BANK_A-VAL
          FAULT_BANK_A
          FAULT_BANK_B-VAL
          FAULT_BANK_B
          WARNING_BANK_A-VAL
          WARNING_BANK_A
          WARNING_BANK_B-VAL
          WARNING_BANK_B
))