(cl:in-package kortex_driver-msg)
(cl:export '(CUSTOM_DATA_ID-VAL
          CUSTOM_DATA_ID
          CUSTOM_DATA_0-VAL
          CUSTOM_DATA_0
          CUSTOM_DATA_1-VAL
          CUSTOM_DATA_1
          CUSTOM_DATA_2-VAL
          CUSTOM_DATA_2
          CUSTOM_DATA_3-VAL
          CUSTOM_DATA_3
          CUSTOM_DATA_4-VAL
          CUSTOM_DATA_4
          CUSTOM_DATA_5-VAL
          CUSTOM_DATA_5
          CUSTOM_DATA_6-VAL
          CUSTOM_DATA_6
          CUSTOM_DATA_7-VAL
          CUSTOM_DATA_7
          CUSTOM_DATA_8-VAL
          CUSTOM_DATA_8
          CUSTOM_DATA_9-VAL
          CUSTOM_DATA_9
          CUSTOM_DATA_10-VAL
          CUSTOM_DATA_10
          CUSTOM_DATA_11-VAL
          CUSTOM_DATA_11
          CUSTOM_DATA_12-VAL
          CUSTOM_DATA_12
          CUSTOM_DATA_13-VAL
          CUSTOM_DATA_13
          CUSTOM_DATA_14-VAL
          CUSTOM_DATA_14
          CUSTOM_DATA_15-VAL
          CUSTOM_DATA_15
))