(cl:in-package kortex_driver-msg)
(cl:export '(GROUP_HANDLE-VAL
          GROUP_HANDLE
          NAME-VAL
          NAME
          RELATED_MAPPING_HANDLE-VAL
          RELATED_MAPPING_HANDLE
          PARENT_GROUP_HANDLE-VAL
          PARENT_GROUP_HANDLE
          CHILDREN_MAP_GROUP_HANDLES-VAL
          CHILDREN_MAP_GROUP_HANDLES
          MAP_HANDLES-VAL
          MAP_HANDLES
          APPLICATION_DATA-VAL
          APPLICATION_DATA
))