; Auto-generated. Do not edit!


(cl:in-package kortex_driver-msg)


;//! \htmlinclude Base_SafetyIdentifier.msg.html

(cl:defclass <Base_SafetyIdentifier> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass Base_SafetyIdentifier (<Base_SafetyIdentifier>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Base_SafetyIdentifier>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Base_SafetyIdentifier)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kortex_driver-msg:<Base_SafetyIdentifier> is deprecated: use kortex_driver-msg:Base_SafetyIdentifier instead.")))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<Base_SafetyIdentifier>)))
    "Constants for message type '<Base_SafetyIdentifier>"
  '((:UNSPECIFIED_BASE_SAFETY_IDENTIFIER . 0)
    (:FIRMWARE_UPDATE_FAILURE . 1)
    (:EXTERNAL_COMMUNICATION_ERROR . 2)
    (:MAXIMUM_AMBIENT_TEMPERATURE . 4)
    (:MAXIMUM_CORE_TEMPERATURE . 8)
    (:JOINT_FAULT . 16)
    (:CYCLIC_DATA_JITTER . 32)
    (:REACHED_MAXIMUM_EVENT_LOGS . 64)
    (:NO_KINEMATICS_SUPPORT . 128)
    (:ABOVE_MAXIMUM_DOF . 256)
    (:NETWORK_ERROR . 512)
    (:UNABLE_TO_REACH_POSE . 1024)
    (:JOINT_DETECTION_ERROR . 2048)
    (:NETWORK_INITIALIZATION_ERROR . 4096)
    (:MAXIMUM_CURRENT . 8192)
    (:MAXIMUM_VOLTAGE . 16384)
    (:MINIMUM_VOLTAGE . 32768)
    (:MAXIMUM_END_EFFECTOR_TRANSLATION_VELOCITY . 65536)
    (:MAXIMUM_END_EFFECTOR_ORIENTATION_VELOCITY . 131072)
    (:MAXIMUM_END_EFFECTOR_TRANSLATION_ACCELERATION . 262144)
    (:MAXIMUM_END_EFFECTOR_ORIENTATION_ACCELERATION . 524288)
    (:MAXIMUM_END_EFFECTOR_TRANSLATION_FORCE . 1048576)
    (:MAXIMUM_END_EFFECTOR_ORIENTATION_FORCE . 2097152)
    (:MAXIMUM_END_EFFECTOR_PAYLOAD . 4194304)
    (:EMERGENCY_STOP_ACTIVATED . 8388608)
    (:EMERGENCY_LINE_ACTIVATED . 16777216)
    (:INRUSH_CURRENT_LIMITER_FAULT . 33554432)
    (:NVRAM_CORRUPTED . 67108864)
    (:INCOMPATIBLE_FIRMWARE_VERSION . 134217728)
    (:POWERON_SELF_TEST_FAILURE . 268435456)
    (:DISCRETE_INPUT_STUCK_ACTIVE . 536870912)
    (:ARM_INTO_ILLEGAL_POSITION . 1073741824))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'Base_SafetyIdentifier)))
    "Constants for message type 'Base_SafetyIdentifier"
  '((:UNSPECIFIED_BASE_SAFETY_IDENTIFIER . 0)
    (:FIRMWARE_UPDATE_FAILURE . 1)
    (:EXTERNAL_COMMUNICATION_ERROR . 2)
    (:MAXIMUM_AMBIENT_TEMPERATURE . 4)
    (:MAXIMUM_CORE_TEMPERATURE . 8)
    (:JOINT_FAULT . 16)
    (:CYCLIC_DATA_JITTER . 32)
    (:REACHED_MAXIMUM_EVENT_LOGS . 64)
    (:NO_KINEMATICS_SUPPORT . 128)
    (:ABOVE_MAXIMUM_DOF . 256)
    (:NETWORK_ERROR . 512)
    (:UNABLE_TO_REACH_POSE . 1024)
    (:JOINT_DETECTION_ERROR . 2048)
    (:NETWORK_INITIALIZATION_ERROR . 4096)
    (:MAXIMUM_CURRENT . 8192)
    (:MAXIMUM_VOLTAGE . 16384)
    (:MINIMUM_VOLTAGE . 32768)
    (:MAXIMUM_END_EFFECTOR_TRANSLATION_VELOCITY . 65536)
    (:MAXIMUM_END_EFFECTOR_ORIENTATION_VELOCITY . 131072)
    (:MAXIMUM_END_EFFECTOR_TRANSLATION_ACCELERATION . 262144)
    (:MAXIMUM_END_EFFECTOR_ORIENTATION_ACCELERATION . 524288)
    (:MAXIMUM_END_EFFECTOR_TRANSLATION_FORCE . 1048576)
    (:MAXIMUM_END_EFFECTOR_ORIENTATION_FORCE . 2097152)
    (:MAXIMUM_END_EFFECTOR_PAYLOAD . 4194304)
    (:EMERGENCY_STOP_ACTIVATED . 8388608)
    (:EMERGENCY_LINE_ACTIVATED . 16777216)
    (:INRUSH_CURRENT_LIMITER_FAULT . 33554432)
    (:NVRAM_CORRUPTED . 67108864)
    (:INCOMPATIBLE_FIRMWARE_VERSION . 134217728)
    (:POWERON_SELF_TEST_FAILURE . 268435456)
    (:DISCRETE_INPUT_STUCK_ACTIVE . 536870912)
    (:ARM_INTO_ILLEGAL_POSITION . 1073741824))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Base_SafetyIdentifier>) ostream)
  "Serializes a message object of type '<Base_SafetyIdentifier>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Base_SafetyIdentifier>) istream)
  "Deserializes a message object of type '<Base_SafetyIdentifier>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Base_SafetyIdentifier>)))
  "Returns string type for a message object of type '<Base_SafetyIdentifier>"
  "kortex_driver/Base_SafetyIdentifier")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Base_SafetyIdentifier)))
  "Returns string type for a message object of type 'Base_SafetyIdentifier"
  "kortex_driver/Base_SafetyIdentifier")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Base_SafetyIdentifier>)))
  "Returns md5sum for a message object of type '<Base_SafetyIdentifier>"
  "2792acd1b9a60f6127a7d70c0807df25")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Base_SafetyIdentifier)))
  "Returns md5sum for a message object of type 'Base_SafetyIdentifier"
  "2792acd1b9a60f6127a7d70c0807df25")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Base_SafetyIdentifier>)))
  "Returns full string definition for message of type '<Base_SafetyIdentifier>"
  (cl:format cl:nil "~%uint32 UNSPECIFIED_BASE_SAFETY_IDENTIFIER = 0~%~%uint32 FIRMWARE_UPDATE_FAILURE = 1~%~%uint32 EXTERNAL_COMMUNICATION_ERROR = 2~%~%uint32 MAXIMUM_AMBIENT_TEMPERATURE = 4~%~%uint32 MAXIMUM_CORE_TEMPERATURE = 8~%~%uint32 JOINT_FAULT = 16~%~%uint32 CYCLIC_DATA_JITTER = 32~%~%uint32 REACHED_MAXIMUM_EVENT_LOGS = 64~%~%uint32 NO_KINEMATICS_SUPPORT = 128~%~%uint32 ABOVE_MAXIMUM_DOF = 256~%~%uint32 NETWORK_ERROR = 512~%~%uint32 UNABLE_TO_REACH_POSE = 1024~%~%uint32 JOINT_DETECTION_ERROR = 2048~%~%uint32 NETWORK_INITIALIZATION_ERROR = 4096~%~%uint32 MAXIMUM_CURRENT = 8192~%~%uint32 MAXIMUM_VOLTAGE = 16384~%~%uint32 MINIMUM_VOLTAGE = 32768~%~%uint32 MAXIMUM_END_EFFECTOR_TRANSLATION_VELOCITY = 65536~%~%uint32 MAXIMUM_END_EFFECTOR_ORIENTATION_VELOCITY = 131072~%~%uint32 MAXIMUM_END_EFFECTOR_TRANSLATION_ACCELERATION = 262144~%~%uint32 MAXIMUM_END_EFFECTOR_ORIENTATION_ACCELERATION = 524288~%~%uint32 MAXIMUM_END_EFFECTOR_TRANSLATION_FORCE = 1048576~%~%uint32 MAXIMUM_END_EFFECTOR_ORIENTATION_FORCE = 2097152~%~%uint32 MAXIMUM_END_EFFECTOR_PAYLOAD = 4194304~%~%uint32 EMERGENCY_STOP_ACTIVATED = 8388608~%~%uint32 EMERGENCY_LINE_ACTIVATED = 16777216~%~%uint32 INRUSH_CURRENT_LIMITER_FAULT = 33554432~%~%uint32 NVRAM_CORRUPTED = 67108864~%~%uint32 INCOMPATIBLE_FIRMWARE_VERSION = 134217728~%~%uint32 POWERON_SELF_TEST_FAILURE = 268435456~%~%uint32 DISCRETE_INPUT_STUCK_ACTIVE = 536870912~%~%uint32 ARM_INTO_ILLEGAL_POSITION = 1073741824~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Base_SafetyIdentifier)))
  "Returns full string definition for message of type 'Base_SafetyIdentifier"
  (cl:format cl:nil "~%uint32 UNSPECIFIED_BASE_SAFETY_IDENTIFIER = 0~%~%uint32 FIRMWARE_UPDATE_FAILURE = 1~%~%uint32 EXTERNAL_COMMUNICATION_ERROR = 2~%~%uint32 MAXIMUM_AMBIENT_TEMPERATURE = 4~%~%uint32 MAXIMUM_CORE_TEMPERATURE = 8~%~%uint32 JOINT_FAULT = 16~%~%uint32 CYCLIC_DATA_JITTER = 32~%~%uint32 REACHED_MAXIMUM_EVENT_LOGS = 64~%~%uint32 NO_KINEMATICS_SUPPORT = 128~%~%uint32 ABOVE_MAXIMUM_DOF = 256~%~%uint32 NETWORK_ERROR = 512~%~%uint32 UNABLE_TO_REACH_POSE = 1024~%~%uint32 JOINT_DETECTION_ERROR = 2048~%~%uint32 NETWORK_INITIALIZATION_ERROR = 4096~%~%uint32 MAXIMUM_CURRENT = 8192~%~%uint32 MAXIMUM_VOLTAGE = 16384~%~%uint32 MINIMUM_VOLTAGE = 32768~%~%uint32 MAXIMUM_END_EFFECTOR_TRANSLATION_VELOCITY = 65536~%~%uint32 MAXIMUM_END_EFFECTOR_ORIENTATION_VELOCITY = 131072~%~%uint32 MAXIMUM_END_EFFECTOR_TRANSLATION_ACCELERATION = 262144~%~%uint32 MAXIMUM_END_EFFECTOR_ORIENTATION_ACCELERATION = 524288~%~%uint32 MAXIMUM_END_EFFECTOR_TRANSLATION_FORCE = 1048576~%~%uint32 MAXIMUM_END_EFFECTOR_ORIENTATION_FORCE = 2097152~%~%uint32 MAXIMUM_END_EFFECTOR_PAYLOAD = 4194304~%~%uint32 EMERGENCY_STOP_ACTIVATED = 8388608~%~%uint32 EMERGENCY_LINE_ACTIVATED = 16777216~%~%uint32 INRUSH_CURRENT_LIMITER_FAULT = 33554432~%~%uint32 NVRAM_CORRUPTED = 67108864~%~%uint32 INCOMPATIBLE_FIRMWARE_VERSION = 134217728~%~%uint32 POWERON_SELF_TEST_FAILURE = 268435456~%~%uint32 DISCRETE_INPUT_STUCK_ACTIVE = 536870912~%~%uint32 ARM_INTO_ILLEGAL_POSITION = 1073741824~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Base_SafetyIdentifier>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Base_SafetyIdentifier>))
  "Converts a ROS message object to a list"
  (cl:list 'Base_SafetyIdentifier
))
