; Auto-generated. Do not edit!


(cl:in-package kortex_driver-msg)


;//! \htmlinclude ConfigurationChangeNotification_configuration_change.msg.html

(cl:defclass <ConfigurationChangeNotification_configuration_change> (roslisp-msg-protocol:ros-message)
  ((sequence_handle
    :reader sequence_handle
    :initarg :sequence_handle
    :type (cl:vector kortex_driver-msg:SequenceHandle)
   :initform (cl:make-array 0 :element-type 'kortex_driver-msg:SequenceHandle :initial-element (cl:make-instance 'kortex_driver-msg:SequenceHandle)))
   (action_handle
    :reader action_handle
    :initarg :action_handle
    :type (cl:vector kortex_driver-msg:ActionHandle)
   :initform (cl:make-array 0 :element-type 'kortex_driver-msg:ActionHandle :initial-element (cl:make-instance 'kortex_driver-msg:ActionHandle)))
   (mapping_handle
    :reader mapping_handle
    :initarg :mapping_handle
    :type (cl:vector kortex_driver-msg:MappingHandle)
   :initform (cl:make-array 0 :element-type 'kortex_driver-msg:MappingHandle :initial-element (cl:make-instance 'kortex_driver-msg:MappingHandle)))
   (map_group_handle
    :reader map_group_handle
    :initarg :map_group_handle
    :type (cl:vector kortex_driver-msg:MapGroupHandle)
   :initform (cl:make-array 0 :element-type 'kortex_driver-msg:MapGroupHandle :initial-element (cl:make-instance 'kortex_driver-msg:MapGroupHandle)))
   (map_handle
    :reader map_handle
    :initarg :map_handle
    :type (cl:vector kortex_driver-msg:MapHandle)
   :initform (cl:make-array 0 :element-type 'kortex_driver-msg:MapHandle :initial-element (cl:make-instance 'kortex_driver-msg:MapHandle)))
   (user_profile_handle
    :reader user_profile_handle
    :initarg :user_profile_handle
    :type (cl:vector kortex_driver-msg:UserProfileHandle)
   :initform (cl:make-array 0 :element-type 'kortex_driver-msg:UserProfileHandle :initial-element (cl:make-instance 'kortex_driver-msg:UserProfileHandle)))
   (protection_zone_handle
    :reader protection_zone_handle
    :initarg :protection_zone_handle
    :type (cl:vector kortex_driver-msg:ProtectionZoneHandle)
   :initform (cl:make-array 0 :element-type 'kortex_driver-msg:ProtectionZoneHandle :initial-element (cl:make-instance 'kortex_driver-msg:ProtectionZoneHandle)))
   (safety_handle
    :reader safety_handle
    :initarg :safety_handle
    :type (cl:vector kortex_driver-msg:SafetyHandle)
   :initform (cl:make-array 0 :element-type 'kortex_driver-msg:SafetyHandle :initial-element (cl:make-instance 'kortex_driver-msg:SafetyHandle)))
   (network_handle
    :reader network_handle
    :initarg :network_handle
    :type (cl:vector kortex_driver-msg:NetworkHandle)
   :initform (cl:make-array 0 :element-type 'kortex_driver-msg:NetworkHandle :initial-element (cl:make-instance 'kortex_driver-msg:NetworkHandle)))
   (ssid
    :reader ssid
    :initarg :ssid
    :type (cl:vector kortex_driver-msg:Ssid)
   :initform (cl:make-array 0 :element-type 'kortex_driver-msg:Ssid :initial-element (cl:make-instance 'kortex_driver-msg:Ssid)))
   (controller_handle
    :reader controller_handle
    :initarg :controller_handle
    :type (cl:vector kortex_driver-msg:ControllerHandle)
   :initform (cl:make-array 0 :element-type 'kortex_driver-msg:ControllerHandle :initial-element (cl:make-instance 'kortex_driver-msg:ControllerHandle))))
)

(cl:defclass ConfigurationChangeNotification_configuration_change (<ConfigurationChangeNotification_configuration_change>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ConfigurationChangeNotification_configuration_change>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ConfigurationChangeNotification_configuration_change)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kortex_driver-msg:<ConfigurationChangeNotification_configuration_change> is deprecated: use kortex_driver-msg:ConfigurationChangeNotification_configuration_change instead.")))

(cl:ensure-generic-function 'sequence_handle-val :lambda-list '(m))
(cl:defmethod sequence_handle-val ((m <ConfigurationChangeNotification_configuration_change>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kortex_driver-msg:sequence_handle-val is deprecated.  Use kortex_driver-msg:sequence_handle instead.")
  (sequence_handle m))

(cl:ensure-generic-function 'action_handle-val :lambda-list '(m))
(cl:defmethod action_handle-val ((m <ConfigurationChangeNotification_configuration_change>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kortex_driver-msg:action_handle-val is deprecated.  Use kortex_driver-msg:action_handle instead.")
  (action_handle m))

(cl:ensure-generic-function 'mapping_handle-val :lambda-list '(m))
(cl:defmethod mapping_handle-val ((m <ConfigurationChangeNotification_configuration_change>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kortex_driver-msg:mapping_handle-val is deprecated.  Use kortex_driver-msg:mapping_handle instead.")
  (mapping_handle m))

(cl:ensure-generic-function 'map_group_handle-val :lambda-list '(m))
(cl:defmethod map_group_handle-val ((m <ConfigurationChangeNotification_configuration_change>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kortex_driver-msg:map_group_handle-val is deprecated.  Use kortex_driver-msg:map_group_handle instead.")
  (map_group_handle m))

(cl:ensure-generic-function 'map_handle-val :lambda-list '(m))
(cl:defmethod map_handle-val ((m <ConfigurationChangeNotification_configuration_change>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kortex_driver-msg:map_handle-val is deprecated.  Use kortex_driver-msg:map_handle instead.")
  (map_handle m))

(cl:ensure-generic-function 'user_profile_handle-val :lambda-list '(m))
(cl:defmethod user_profile_handle-val ((m <ConfigurationChangeNotification_configuration_change>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kortex_driver-msg:user_profile_handle-val is deprecated.  Use kortex_driver-msg:user_profile_handle instead.")
  (user_profile_handle m))

(cl:ensure-generic-function 'protection_zone_handle-val :lambda-list '(m))
(cl:defmethod protection_zone_handle-val ((m <ConfigurationChangeNotification_configuration_change>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kortex_driver-msg:protection_zone_handle-val is deprecated.  Use kortex_driver-msg:protection_zone_handle instead.")
  (protection_zone_handle m))

(cl:ensure-generic-function 'safety_handle-val :lambda-list '(m))
(cl:defmethod safety_handle-val ((m <ConfigurationChangeNotification_configuration_change>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kortex_driver-msg:safety_handle-val is deprecated.  Use kortex_driver-msg:safety_handle instead.")
  (safety_handle m))

(cl:ensure-generic-function 'network_handle-val :lambda-list '(m))
(cl:defmethod network_handle-val ((m <ConfigurationChangeNotification_configuration_change>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kortex_driver-msg:network_handle-val is deprecated.  Use kortex_driver-msg:network_handle instead.")
  (network_handle m))

(cl:ensure-generic-function 'ssid-val :lambda-list '(m))
(cl:defmethod ssid-val ((m <ConfigurationChangeNotification_configuration_change>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kortex_driver-msg:ssid-val is deprecated.  Use kortex_driver-msg:ssid instead.")
  (ssid m))

(cl:ensure-generic-function 'controller_handle-val :lambda-list '(m))
(cl:defmethod controller_handle-val ((m <ConfigurationChangeNotification_configuration_change>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kortex_driver-msg:controller_handle-val is deprecated.  Use kortex_driver-msg:controller_handle instead.")
  (controller_handle m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ConfigurationChangeNotification_configuration_change>) ostream)
  "Serializes a message object of type '<ConfigurationChangeNotification_configuration_change>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'sequence_handle))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'sequence_handle))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'action_handle))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'action_handle))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'mapping_handle))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'mapping_handle))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'map_group_handle))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'map_group_handle))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'map_handle))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'map_handle))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'user_profile_handle))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'user_profile_handle))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'protection_zone_handle))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'protection_zone_handle))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'safety_handle))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'safety_handle))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'network_handle))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'network_handle))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'ssid))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'ssid))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'controller_handle))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'controller_handle))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ConfigurationChangeNotification_configuration_change>) istream)
  "Deserializes a message object of type '<ConfigurationChangeNotification_configuration_change>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'sequence_handle) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'sequence_handle)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'kortex_driver-msg:SequenceHandle))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'action_handle) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'action_handle)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'kortex_driver-msg:ActionHandle))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'mapping_handle) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'mapping_handle)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'kortex_driver-msg:MappingHandle))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'map_group_handle) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'map_group_handle)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'kortex_driver-msg:MapGroupHandle))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'map_handle) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'map_handle)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'kortex_driver-msg:MapHandle))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'user_profile_handle) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'user_profile_handle)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'kortex_driver-msg:UserProfileHandle))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'protection_zone_handle) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'protection_zone_handle)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'kortex_driver-msg:ProtectionZoneHandle))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'safety_handle) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'safety_handle)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'kortex_driver-msg:SafetyHandle))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'network_handle) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'network_handle)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'kortex_driver-msg:NetworkHandle))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'ssid) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'ssid)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'kortex_driver-msg:Ssid))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'controller_handle) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'controller_handle)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'kortex_driver-msg:ControllerHandle))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ConfigurationChangeNotification_configuration_change>)))
  "Returns string type for a message object of type '<ConfigurationChangeNotification_configuration_change>"
  "kortex_driver/ConfigurationChangeNotification_configuration_change")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ConfigurationChangeNotification_configuration_change)))
  "Returns string type for a message object of type 'ConfigurationChangeNotification_configuration_change"
  "kortex_driver/ConfigurationChangeNotification_configuration_change")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ConfigurationChangeNotification_configuration_change>)))
  "Returns md5sum for a message object of type '<ConfigurationChangeNotification_configuration_change>"
  "da6a00bf2364ba1e44afbbbd7c77db5b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ConfigurationChangeNotification_configuration_change)))
  "Returns md5sum for a message object of type 'ConfigurationChangeNotification_configuration_change"
  "da6a00bf2364ba1e44afbbbd7c77db5b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ConfigurationChangeNotification_configuration_change>)))
  "Returns full string definition for message of type '<ConfigurationChangeNotification_configuration_change>"
  (cl:format cl:nil "~%SequenceHandle[] sequence_handle~%ActionHandle[] action_handle~%MappingHandle[] mapping_handle~%MapGroupHandle[] map_group_handle~%MapHandle[] map_handle~%UserProfileHandle[] user_profile_handle~%ProtectionZoneHandle[] protection_zone_handle~%SafetyHandle[] safety_handle~%NetworkHandle[] network_handle~%Ssid[] ssid~%ControllerHandle[] controller_handle~%================================================================================~%MSG: kortex_driver/SequenceHandle~%~%uint32 identifier~%uint32 permission~%================================================================================~%MSG: kortex_driver/ActionHandle~%~%uint32 identifier~%uint32 action_type~%uint32 permission~%================================================================================~%MSG: kortex_driver/MappingHandle~%~%uint32 identifier~%uint32 permission~%================================================================================~%MSG: kortex_driver/MapGroupHandle~%~%uint32 identifier~%uint32 permission~%================================================================================~%MSG: kortex_driver/MapHandle~%~%uint32 identifier~%uint32 permission~%================================================================================~%MSG: kortex_driver/UserProfileHandle~%~%uint32 identifier~%uint32 permission~%================================================================================~%MSG: kortex_driver/ProtectionZoneHandle~%~%uint32 identifier~%uint32 permission~%================================================================================~%MSG: kortex_driver/SafetyHandle~%~%uint32 identifier~%================================================================================~%MSG: kortex_driver/NetworkHandle~%~%uint32 type~%================================================================================~%MSG: kortex_driver/Ssid~%~%string identifier~%================================================================================~%MSG: kortex_driver/ControllerHandle~%~%uint32 type~%uint32 controller_identifier~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ConfigurationChangeNotification_configuration_change)))
  "Returns full string definition for message of type 'ConfigurationChangeNotification_configuration_change"
  (cl:format cl:nil "~%SequenceHandle[] sequence_handle~%ActionHandle[] action_handle~%MappingHandle[] mapping_handle~%MapGroupHandle[] map_group_handle~%MapHandle[] map_handle~%UserProfileHandle[] user_profile_handle~%ProtectionZoneHandle[] protection_zone_handle~%SafetyHandle[] safety_handle~%NetworkHandle[] network_handle~%Ssid[] ssid~%ControllerHandle[] controller_handle~%================================================================================~%MSG: kortex_driver/SequenceHandle~%~%uint32 identifier~%uint32 permission~%================================================================================~%MSG: kortex_driver/ActionHandle~%~%uint32 identifier~%uint32 action_type~%uint32 permission~%================================================================================~%MSG: kortex_driver/MappingHandle~%~%uint32 identifier~%uint32 permission~%================================================================================~%MSG: kortex_driver/MapGroupHandle~%~%uint32 identifier~%uint32 permission~%================================================================================~%MSG: kortex_driver/MapHandle~%~%uint32 identifier~%uint32 permission~%================================================================================~%MSG: kortex_driver/UserProfileHandle~%~%uint32 identifier~%uint32 permission~%================================================================================~%MSG: kortex_driver/ProtectionZoneHandle~%~%uint32 identifier~%uint32 permission~%================================================================================~%MSG: kortex_driver/SafetyHandle~%~%uint32 identifier~%================================================================================~%MSG: kortex_driver/NetworkHandle~%~%uint32 type~%================================================================================~%MSG: kortex_driver/Ssid~%~%string identifier~%================================================================================~%MSG: kortex_driver/ControllerHandle~%~%uint32 type~%uint32 controller_identifier~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ConfigurationChangeNotification_configuration_change>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'sequence_handle) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'action_handle) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'mapping_handle) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'map_group_handle) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'map_handle) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'user_profile_handle) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'protection_zone_handle) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'safety_handle) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'network_handle) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'ssid) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'controller_handle) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ConfigurationChangeNotification_configuration_change>))
  "Converts a ROS message object to a list"
  (cl:list 'ConfigurationChangeNotification_configuration_change
    (cl:cons ':sequence_handle (sequence_handle msg))
    (cl:cons ':action_handle (action_handle msg))
    (cl:cons ':mapping_handle (mapping_handle msg))
    (cl:cons ':map_group_handle (map_group_handle msg))
    (cl:cons ':map_handle (map_handle msg))
    (cl:cons ':user_profile_handle (user_profile_handle msg))
    (cl:cons ':protection_zone_handle (protection_zone_handle msg))
    (cl:cons ':safety_handle (safety_handle msg))
    (cl:cons ':network_handle (network_handle msg))
    (cl:cons ':ssid (ssid msg))
    (cl:cons ':controller_handle (controller_handle msg))
))
