// Generated by gencpp from file kortex_driver/Base_GetCapSenseConfig.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_BASE_GETCAPSENSECONFIG_H
#define KORTEX_DRIVER_MESSAGE_BASE_GETCAPSENSECONFIG_H

#include <ros/service_traits.h>


#include <kortex_driver/Base_GetCapSenseConfigRequest.h>
#include <kortex_driver/Base_GetCapSenseConfigResponse.h>


namespace kortex_driver
{

struct Base_GetCapSenseConfig
{

typedef Base_GetCapSenseConfigRequest Request;
typedef Base_GetCapSenseConfigResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Base_GetCapSenseConfig
} // namespace kortex_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kortex_driver::Base_GetCapSenseConfig > {
  static const char* value()
  {
    return "c1e479a50a0c96ec49d735b61e1b4a43";
  }

  static const char* value(const ::kortex_driver::Base_GetCapSenseConfig&) { return value(); }
};

template<>
struct DataType< ::kortex_driver::Base_GetCapSenseConfig > {
  static const char* value()
  {
    return "kortex_driver/Base_GetCapSenseConfig";
  }

  static const char* value(const ::kortex_driver::Base_GetCapSenseConfig&) { return value(); }
};


// service_traits::MD5Sum< ::kortex_driver::Base_GetCapSenseConfigRequest> should match
// service_traits::MD5Sum< ::kortex_driver::Base_GetCapSenseConfig >
template<>
struct MD5Sum< ::kortex_driver::Base_GetCapSenseConfigRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kortex_driver::Base_GetCapSenseConfig >::value();
  }
  static const char* value(const ::kortex_driver::Base_GetCapSenseConfigRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kortex_driver::Base_GetCapSenseConfigRequest> should match
// service_traits::DataType< ::kortex_driver::Base_GetCapSenseConfig >
template<>
struct DataType< ::kortex_driver::Base_GetCapSenseConfigRequest>
{
  static const char* value()
  {
    return DataType< ::kortex_driver::Base_GetCapSenseConfig >::value();
  }
  static const char* value(const ::kortex_driver::Base_GetCapSenseConfigRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kortex_driver::Base_GetCapSenseConfigResponse> should match
// service_traits::MD5Sum< ::kortex_driver::Base_GetCapSenseConfig >
template<>
struct MD5Sum< ::kortex_driver::Base_GetCapSenseConfigResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kortex_driver::Base_GetCapSenseConfig >::value();
  }
  static const char* value(const ::kortex_driver::Base_GetCapSenseConfigResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kortex_driver::Base_GetCapSenseConfigResponse> should match
// service_traits::DataType< ::kortex_driver::Base_GetCapSenseConfig >
template<>
struct DataType< ::kortex_driver::Base_GetCapSenseConfigResponse>
{
  static const char* value()
  {
    return DataType< ::kortex_driver::Base_GetCapSenseConfig >::value();
  }
  static const char* value(const ::kortex_driver::Base_GetCapSenseConfigResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_BASE_GETCAPSENSECONFIG_H
