// Generated by gencpp from file kortex_driver/Base_ClearFaults.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_BASE_CLEARFAULTS_H
#define KORTEX_DRIVER_MESSAGE_BASE_CLEARFAULTS_H

#include <ros/service_traits.h>


#include <kortex_driver/Base_ClearFaultsRequest.h>
#include <kortex_driver/Base_ClearFaultsResponse.h>


namespace kortex_driver
{

struct Base_ClearFaults
{

typedef Base_ClearFaultsRequest Request;
typedef Base_ClearFaultsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Base_ClearFaults
} // namespace kortex_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kortex_driver::Base_ClearFaults > {
  static const char* value()
  {
    return "f335b819dc59099fe3124b36f140ad07";
  }

  static const char* value(const ::kortex_driver::Base_ClearFaults&) { return value(); }
};

template<>
struct DataType< ::kortex_driver::Base_ClearFaults > {
  static const char* value()
  {
    return "kortex_driver/Base_ClearFaults";
  }

  static const char* value(const ::kortex_driver::Base_ClearFaults&) { return value(); }
};


// service_traits::MD5Sum< ::kortex_driver::Base_ClearFaultsRequest> should match
// service_traits::MD5Sum< ::kortex_driver::Base_ClearFaults >
template<>
struct MD5Sum< ::kortex_driver::Base_ClearFaultsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kortex_driver::Base_ClearFaults >::value();
  }
  static const char* value(const ::kortex_driver::Base_ClearFaultsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kortex_driver::Base_ClearFaultsRequest> should match
// service_traits::DataType< ::kortex_driver::Base_ClearFaults >
template<>
struct DataType< ::kortex_driver::Base_ClearFaultsRequest>
{
  static const char* value()
  {
    return DataType< ::kortex_driver::Base_ClearFaults >::value();
  }
  static const char* value(const ::kortex_driver::Base_ClearFaultsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kortex_driver::Base_ClearFaultsResponse> should match
// service_traits::MD5Sum< ::kortex_driver::Base_ClearFaults >
template<>
struct MD5Sum< ::kortex_driver::Base_ClearFaultsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kortex_driver::Base_ClearFaults >::value();
  }
  static const char* value(const ::kortex_driver::Base_ClearFaultsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kortex_driver::Base_ClearFaultsResponse> should match
// service_traits::DataType< ::kortex_driver::Base_ClearFaults >
template<>
struct DataType< ::kortex_driver::Base_ClearFaultsResponse>
{
  static const char* value()
  {
    return DataType< ::kortex_driver::Base_ClearFaults >::value();
  }
  static const char* value(const ::kortex_driver::Base_ClearFaultsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_BASE_CLEARFAULTS_H
