// Generated by gencpp from file kortex_driver/ConstrainedOrientation.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_CONSTRAINEDORIENTATION_H
#define KORTEX_DRIVER_MESSAGE_CONSTRAINEDORIENTATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kortex_driver/Orientation.h>
#include <kortex_driver/CartesianTrajectoryConstraint.h>

namespace kortex_driver
{
template <class ContainerAllocator>
struct ConstrainedOrientation_
{
  typedef ConstrainedOrientation_<ContainerAllocator> Type;

  ConstrainedOrientation_()
    : target_orientation()
    , constraint()  {
    }
  ConstrainedOrientation_(const ContainerAllocator& _alloc)
    : target_orientation(_alloc)
    , constraint(_alloc)  {
  (void)_alloc;
    }



   typedef  ::kortex_driver::Orientation_<ContainerAllocator>  _target_orientation_type;
  _target_orientation_type target_orientation;

   typedef  ::kortex_driver::CartesianTrajectoryConstraint_<ContainerAllocator>  _constraint_type;
  _constraint_type constraint;





  typedef boost::shared_ptr< ::kortex_driver::ConstrainedOrientation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kortex_driver::ConstrainedOrientation_<ContainerAllocator> const> ConstPtr;

}; // struct ConstrainedOrientation_

typedef ::kortex_driver::ConstrainedOrientation_<std::allocator<void> > ConstrainedOrientation;

typedef boost::shared_ptr< ::kortex_driver::ConstrainedOrientation > ConstrainedOrientationPtr;
typedef boost::shared_ptr< ::kortex_driver::ConstrainedOrientation const> ConstrainedOrientationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kortex_driver::ConstrainedOrientation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kortex_driver::ConstrainedOrientation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kortex_driver::ConstrainedOrientation_<ContainerAllocator1> & lhs, const ::kortex_driver::ConstrainedOrientation_<ContainerAllocator2> & rhs)
{
  return lhs.target_orientation == rhs.target_orientation &&
    lhs.constraint == rhs.constraint;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kortex_driver::ConstrainedOrientation_<ContainerAllocator1> & lhs, const ::kortex_driver::ConstrainedOrientation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kortex_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::ConstrainedOrientation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::ConstrainedOrientation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::ConstrainedOrientation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::ConstrainedOrientation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::ConstrainedOrientation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::ConstrainedOrientation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kortex_driver::ConstrainedOrientation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "15f399eb15570e6ba491b979fdea9cfd";
  }

  static const char* value(const ::kortex_driver::ConstrainedOrientation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x15f399eb15570e6bULL;
  static const uint64_t static_value2 = 0xa491b979fdea9cfdULL;
};

template<class ContainerAllocator>
struct DataType< ::kortex_driver::ConstrainedOrientation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kortex_driver/ConstrainedOrientation";
  }

  static const char* value(const ::kortex_driver::ConstrainedOrientation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kortex_driver::ConstrainedOrientation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"Orientation target_orientation\n"
"CartesianTrajectoryConstraint constraint\n"
"================================================================================\n"
"MSG: kortex_driver/Orientation\n"
"\n"
"float32 theta_x\n"
"float32 theta_y\n"
"float32 theta_z\n"
"================================================================================\n"
"MSG: kortex_driver/CartesianTrajectoryConstraint\n"
"\n"
"CartesianTrajectoryConstraint_type oneof_type\n"
"================================================================================\n"
"MSG: kortex_driver/CartesianTrajectoryConstraint_type\n"
"\n"
"CartesianSpeed[] speed\n"
"uint32[] duration\n"
"================================================================================\n"
"MSG: kortex_driver/CartesianSpeed\n"
"\n"
"float32 translation\n"
"float32 orientation\n"
;
  }

  static const char* value(const ::kortex_driver::ConstrainedOrientation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kortex_driver::ConstrainedOrientation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_orientation);
      stream.next(m.constraint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConstrainedOrientation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kortex_driver::ConstrainedOrientation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kortex_driver::ConstrainedOrientation_<ContainerAllocator>& v)
  {
    s << indent << "target_orientation: ";
    s << std::endl;
    Printer< ::kortex_driver::Orientation_<ContainerAllocator> >::stream(s, indent + "  ", v.target_orientation);
    s << indent << "constraint: ";
    s << std::endl;
    Printer< ::kortex_driver::CartesianTrajectoryConstraint_<ContainerAllocator> >::stream(s, indent + "  ", v.constraint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_CONSTRAINEDORIENTATION_H
