// Generated by gencpp from file kortex_driver/ControllerElementHandle.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_CONTROLLERELEMENTHANDLE_H
#define KORTEX_DRIVER_MESSAGE_CONTROLLERELEMENTHANDLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kortex_driver/ControllerHandle.h>
#include <kortex_driver/ControllerElementHandle_identifier.h>

namespace kortex_driver
{
template <class ContainerAllocator>
struct ControllerElementHandle_
{
  typedef ControllerElementHandle_<ContainerAllocator> Type;

  ControllerElementHandle_()
    : controller_handle()
    , oneof_identifier()  {
    }
  ControllerElementHandle_(const ContainerAllocator& _alloc)
    : controller_handle(_alloc)
    , oneof_identifier(_alloc)  {
  (void)_alloc;
    }



   typedef  ::kortex_driver::ControllerHandle_<ContainerAllocator>  _controller_handle_type;
  _controller_handle_type controller_handle;

   typedef  ::kortex_driver::ControllerElementHandle_identifier_<ContainerAllocator>  _oneof_identifier_type;
  _oneof_identifier_type oneof_identifier;





  typedef boost::shared_ptr< ::kortex_driver::ControllerElementHandle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kortex_driver::ControllerElementHandle_<ContainerAllocator> const> ConstPtr;

}; // struct ControllerElementHandle_

typedef ::kortex_driver::ControllerElementHandle_<std::allocator<void> > ControllerElementHandle;

typedef boost::shared_ptr< ::kortex_driver::ControllerElementHandle > ControllerElementHandlePtr;
typedef boost::shared_ptr< ::kortex_driver::ControllerElementHandle const> ControllerElementHandleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kortex_driver::ControllerElementHandle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kortex_driver::ControllerElementHandle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kortex_driver::ControllerElementHandle_<ContainerAllocator1> & lhs, const ::kortex_driver::ControllerElementHandle_<ContainerAllocator2> & rhs)
{
  return lhs.controller_handle == rhs.controller_handle &&
    lhs.oneof_identifier == rhs.oneof_identifier;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kortex_driver::ControllerElementHandle_<ContainerAllocator1> & lhs, const ::kortex_driver::ControllerElementHandle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kortex_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::ControllerElementHandle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::ControllerElementHandle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::ControllerElementHandle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::ControllerElementHandle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::ControllerElementHandle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::ControllerElementHandle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kortex_driver::ControllerElementHandle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c89bd366e7348e92cb61f477829e5ba";
  }

  static const char* value(const ::kortex_driver::ControllerElementHandle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c89bd366e7348e9ULL;
  static const uint64_t static_value2 = 0x2cb61f477829e5baULL;
};

template<class ContainerAllocator>
struct DataType< ::kortex_driver::ControllerElementHandle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kortex_driver/ControllerElementHandle";
  }

  static const char* value(const ::kortex_driver::ControllerElementHandle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kortex_driver::ControllerElementHandle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"ControllerHandle controller_handle\n"
"ControllerElementHandle_identifier oneof_identifier\n"
"================================================================================\n"
"MSG: kortex_driver/ControllerHandle\n"
"\n"
"uint32 type\n"
"uint32 controller_identifier\n"
"================================================================================\n"
"MSG: kortex_driver/ControllerElementHandle_identifier\n"
"\n"
"uint32[] button\n"
"uint32[] axis\n"
;
  }

  static const char* value(const ::kortex_driver::ControllerElementHandle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kortex_driver::ControllerElementHandle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.controller_handle);
      stream.next(m.oneof_identifier);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControllerElementHandle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kortex_driver::ControllerElementHandle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kortex_driver::ControllerElementHandle_<ContainerAllocator>& v)
  {
    s << indent << "controller_handle: ";
    s << std::endl;
    Printer< ::kortex_driver::ControllerHandle_<ContainerAllocator> >::stream(s, indent + "  ", v.controller_handle);
    s << indent << "oneof_identifier: ";
    s << std::endl;
    Printer< ::kortex_driver::ControllerElementHandle_identifier_<ContainerAllocator> >::stream(s, indent + "  ", v.oneof_identifier);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_CONTROLLERELEMENTHANDLE_H
