// Generated by gencpp from file kortex_driver/DeviceHandles.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_DEVICEHANDLES_H
#define KORTEX_DRIVER_MESSAGE_DEVICEHANDLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kortex_driver/DeviceHandle.h>

namespace kortex_driver
{
template <class ContainerAllocator>
struct DeviceHandles_
{
  typedef DeviceHandles_<ContainerAllocator> Type;

  DeviceHandles_()
    : device_handle()  {
    }
  DeviceHandles_(const ContainerAllocator& _alloc)
    : device_handle(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::kortex_driver::DeviceHandle_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::kortex_driver::DeviceHandle_<ContainerAllocator> >::other >  _device_handle_type;
  _device_handle_type device_handle;





  typedef boost::shared_ptr< ::kortex_driver::DeviceHandles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kortex_driver::DeviceHandles_<ContainerAllocator> const> ConstPtr;

}; // struct DeviceHandles_

typedef ::kortex_driver::DeviceHandles_<std::allocator<void> > DeviceHandles;

typedef boost::shared_ptr< ::kortex_driver::DeviceHandles > DeviceHandlesPtr;
typedef boost::shared_ptr< ::kortex_driver::DeviceHandles const> DeviceHandlesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kortex_driver::DeviceHandles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kortex_driver::DeviceHandles_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kortex_driver::DeviceHandles_<ContainerAllocator1> & lhs, const ::kortex_driver::DeviceHandles_<ContainerAllocator2> & rhs)
{
  return lhs.device_handle == rhs.device_handle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kortex_driver::DeviceHandles_<ContainerAllocator1> & lhs, const ::kortex_driver::DeviceHandles_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kortex_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::DeviceHandles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::DeviceHandles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::DeviceHandles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::DeviceHandles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::DeviceHandles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::DeviceHandles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kortex_driver::DeviceHandles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad854635e0d722ce08228e35a86c0173";
  }

  static const char* value(const ::kortex_driver::DeviceHandles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad854635e0d722ceULL;
  static const uint64_t static_value2 = 0x08228e35a86c0173ULL;
};

template<class ContainerAllocator>
struct DataType< ::kortex_driver::DeviceHandles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kortex_driver/DeviceHandles";
  }

  static const char* value(const ::kortex_driver::DeviceHandles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kortex_driver::DeviceHandles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"DeviceHandle[] device_handle\n"
"================================================================================\n"
"MSG: kortex_driver/DeviceHandle\n"
"\n"
"uint32 device_type\n"
"uint32 device_identifier\n"
"uint32 order\n"
;
  }

  static const char* value(const ::kortex_driver::DeviceHandles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kortex_driver::DeviceHandles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.device_handle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeviceHandles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kortex_driver::DeviceHandles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kortex_driver::DeviceHandles_<ContainerAllocator>& v)
  {
    s << indent << "device_handle[]" << std::endl;
    for (size_t i = 0; i < v.device_handle.size(); ++i)
    {
      s << indent << "  device_handle[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::kortex_driver::DeviceHandle_<ContainerAllocator> >::stream(s, indent + "    ", v.device_handle[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_DEVICEHANDLES_H
