// Generated by gencpp from file kortex_driver/EncoderDerivativeParameters.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_ENCODERDERIVATIVEPARAMETERS_H
#define KORTEX_DRIVER_MESSAGE_ENCODERDERIVATIVEPARAMETERS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kortex_driver
{
template <class ContainerAllocator>
struct EncoderDerivativeParameters_
{
  typedef EncoderDerivativeParameters_<ContainerAllocator> Type;

  EncoderDerivativeParameters_()
    : max_window_width(0)
    , min_angle(0.0)  {
    }
  EncoderDerivativeParameters_(const ContainerAllocator& _alloc)
    : max_window_width(0)
    , min_angle(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _max_window_width_type;
  _max_window_width_type max_window_width;

   typedef float _min_angle_type;
  _min_angle_type min_angle;





  typedef boost::shared_ptr< ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator> const> ConstPtr;

}; // struct EncoderDerivativeParameters_

typedef ::kortex_driver::EncoderDerivativeParameters_<std::allocator<void> > EncoderDerivativeParameters;

typedef boost::shared_ptr< ::kortex_driver::EncoderDerivativeParameters > EncoderDerivativeParametersPtr;
typedef boost::shared_ptr< ::kortex_driver::EncoderDerivativeParameters const> EncoderDerivativeParametersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator1> & lhs, const ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator2> & rhs)
{
  return lhs.max_window_width == rhs.max_window_width &&
    lhs.min_angle == rhs.min_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator1> & lhs, const ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kortex_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e0a5e3a584720a2550104b5e1faa434";
  }

  static const char* value(const ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e0a5e3a584720a2ULL;
  static const uint64_t static_value2 = 0x550104b5e1faa434ULL;
};

template<class ContainerAllocator>
struct DataType< ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kortex_driver/EncoderDerivativeParameters";
  }

  static const char* value(const ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"uint32 max_window_width\n"
"float32 min_angle\n"
;
  }

  static const char* value(const ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.max_window_width);
      stream.next(m.min_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EncoderDerivativeParameters_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kortex_driver::EncoderDerivativeParameters_<ContainerAllocator>& v)
  {
    s << indent << "max_window_width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.max_window_width);
    s << indent << "min_angle: ";
    Printer<float>::stream(s, indent + "  ", v.min_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_ENCODERDERIVATIVEPARAMETERS_H
