// Generated by gencpp from file kortex_driver/GetAvailableWifiResponse.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_GETAVAILABLEWIFIRESPONSE_H
#define KORTEX_DRIVER_MESSAGE_GETAVAILABLEWIFIRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kortex_driver/WifiInformationList.h>

namespace kortex_driver
{
template <class ContainerAllocator>
struct GetAvailableWifiResponse_
{
  typedef GetAvailableWifiResponse_<ContainerAllocator> Type;

  GetAvailableWifiResponse_()
    : output()  {
    }
  GetAvailableWifiResponse_(const ContainerAllocator& _alloc)
    : output(_alloc)  {
  (void)_alloc;
    }



   typedef  ::kortex_driver::WifiInformationList_<ContainerAllocator>  _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetAvailableWifiResponse_

typedef ::kortex_driver::GetAvailableWifiResponse_<std::allocator<void> > GetAvailableWifiResponse;

typedef boost::shared_ptr< ::kortex_driver::GetAvailableWifiResponse > GetAvailableWifiResponsePtr;
typedef boost::shared_ptr< ::kortex_driver::GetAvailableWifiResponse const> GetAvailableWifiResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator1> & lhs, const ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator1> & lhs, const ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kortex_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88de91381473bf8e58231cfed636243f";
  }

  static const char* value(const ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88de91381473bf8eULL;
  static const uint64_t static_value2 = 0x58231cfed636243fULL;
};

template<class ContainerAllocator>
struct DataType< ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kortex_driver/GetAvailableWifiResponse";
  }

  static const char* value(const ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "WifiInformationList output\n"
"\n"
"================================================================================\n"
"MSG: kortex_driver/WifiInformationList\n"
"\n"
"WifiInformation[] wifi_information_list\n"
"================================================================================\n"
"MSG: kortex_driver/WifiInformation\n"
"\n"
"Ssid ssid\n"
"uint32 security_type\n"
"uint32 encryption_type\n"
"uint32 signal_quality\n"
"int32 signal_strength\n"
"uint32 frequency\n"
"uint32 channel\n"
"================================================================================\n"
"MSG: kortex_driver/Ssid\n"
"\n"
"string identifier\n"
;
  }

  static const char* value(const ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetAvailableWifiResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kortex_driver::GetAvailableWifiResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    s << std::endl;
    Printer< ::kortex_driver::WifiInformationList_<ContainerAllocator> >::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_GETAVAILABLEWIFIRESPONSE_H
