// Generated by gencpp from file kortex_driver/GetAxisOffsets.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_GETAXISOFFSETS_H
#define KORTEX_DRIVER_MESSAGE_GETAXISOFFSETS_H

#include <ros/service_traits.h>


#include <kortex_driver/GetAxisOffsetsRequest.h>
#include <kortex_driver/GetAxisOffsetsResponse.h>


namespace kortex_driver
{

struct GetAxisOffsets
{

typedef GetAxisOffsetsRequest Request;
typedef GetAxisOffsetsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAxisOffsets
} // namespace kortex_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kortex_driver::GetAxisOffsets > {
  static const char* value()
  {
    return "e0bbfa31b1895cb9c1c9ec4bbac51a98";
  }

  static const char* value(const ::kortex_driver::GetAxisOffsets&) { return value(); }
};

template<>
struct DataType< ::kortex_driver::GetAxisOffsets > {
  static const char* value()
  {
    return "kortex_driver/GetAxisOffsets";
  }

  static const char* value(const ::kortex_driver::GetAxisOffsets&) { return value(); }
};


// service_traits::MD5Sum< ::kortex_driver::GetAxisOffsetsRequest> should match
// service_traits::MD5Sum< ::kortex_driver::GetAxisOffsets >
template<>
struct MD5Sum< ::kortex_driver::GetAxisOffsetsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kortex_driver::GetAxisOffsets >::value();
  }
  static const char* value(const ::kortex_driver::GetAxisOffsetsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kortex_driver::GetAxisOffsetsRequest> should match
// service_traits::DataType< ::kortex_driver::GetAxisOffsets >
template<>
struct DataType< ::kortex_driver::GetAxisOffsetsRequest>
{
  static const char* value()
  {
    return DataType< ::kortex_driver::GetAxisOffsets >::value();
  }
  static const char* value(const ::kortex_driver::GetAxisOffsetsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kortex_driver::GetAxisOffsetsResponse> should match
// service_traits::MD5Sum< ::kortex_driver::GetAxisOffsets >
template<>
struct MD5Sum< ::kortex_driver::GetAxisOffsetsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kortex_driver::GetAxisOffsets >::value();
  }
  static const char* value(const ::kortex_driver::GetAxisOffsetsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kortex_driver::GetAxisOffsetsResponse> should match
// service_traits::DataType< ::kortex_driver::GetAxisOffsets >
template<>
struct DataType< ::kortex_driver::GetAxisOffsetsResponse>
{
  static const char* value()
  {
    return DataType< ::kortex_driver::GetAxisOffsets >::value();
  }
  static const char* value(const ::kortex_driver::GetAxisOffsetsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_GETAXISOFFSETS_H
