// Generated by gencpp from file kortex_driver/GetDesiredSpeedsResponse.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_GETDESIREDSPEEDSRESPONSE_H
#define KORTEX_DRIVER_MESSAGE_GETDESIREDSPEEDSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kortex_driver/DesiredSpeeds.h>

namespace kortex_driver
{
template <class ContainerAllocator>
struct GetDesiredSpeedsResponse_
{
  typedef GetDesiredSpeedsResponse_<ContainerAllocator> Type;

  GetDesiredSpeedsResponse_()
    : output()  {
    }
  GetDesiredSpeedsResponse_(const ContainerAllocator& _alloc)
    : output(_alloc)  {
  (void)_alloc;
    }



   typedef  ::kortex_driver::DesiredSpeeds_<ContainerAllocator>  _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetDesiredSpeedsResponse_

typedef ::kortex_driver::GetDesiredSpeedsResponse_<std::allocator<void> > GetDesiredSpeedsResponse;

typedef boost::shared_ptr< ::kortex_driver::GetDesiredSpeedsResponse > GetDesiredSpeedsResponsePtr;
typedef boost::shared_ptr< ::kortex_driver::GetDesiredSpeedsResponse const> GetDesiredSpeedsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator1> & lhs, const ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator1> & lhs, const ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kortex_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d243d49226b26aa713d823fbebf98e15";
  }

  static const char* value(const ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd243d49226b26aa7ULL;
  static const uint64_t static_value2 = 0x13d823fbebf98e15ULL;
};

template<class ContainerAllocator>
struct DataType< ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kortex_driver/GetDesiredSpeedsResponse";
  }

  static const char* value(const ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "DesiredSpeeds output\n"
"\n"
"================================================================================\n"
"MSG: kortex_driver/DesiredSpeeds\n"
"\n"
"float32 linear\n"
"float32 angular\n"
"float32[] joint_speed\n"
;
  }

  static const char* value(const ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetDesiredSpeedsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kortex_driver::GetDesiredSpeedsResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    s << std::endl;
    Printer< ::kortex_driver::DesiredSpeeds_<ContainerAllocator> >::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_GETDESIREDSPEEDSRESPONSE_H
