// Generated by gencpp from file kortex_driver/GetGPIOState.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_GETGPIOSTATE_H
#define KORTEX_DRIVER_MESSAGE_GETGPIOSTATE_H

#include <ros/service_traits.h>


#include <kortex_driver/GetGPIOStateRequest.h>
#include <kortex_driver/GetGPIOStateResponse.h>


namespace kortex_driver
{

struct GetGPIOState
{

typedef GetGPIOStateRequest Request;
typedef GetGPIOStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGPIOState
} // namespace kortex_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kortex_driver::GetGPIOState > {
  static const char* value()
  {
    return "ee1aa8c7cecf549eed7751c07a3eb88c";
  }

  static const char* value(const ::kortex_driver::GetGPIOState&) { return value(); }
};

template<>
struct DataType< ::kortex_driver::GetGPIOState > {
  static const char* value()
  {
    return "kortex_driver/GetGPIOState";
  }

  static const char* value(const ::kortex_driver::GetGPIOState&) { return value(); }
};


// service_traits::MD5Sum< ::kortex_driver::GetGPIOStateRequest> should match
// service_traits::MD5Sum< ::kortex_driver::GetGPIOState >
template<>
struct MD5Sum< ::kortex_driver::GetGPIOStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kortex_driver::GetGPIOState >::value();
  }
  static const char* value(const ::kortex_driver::GetGPIOStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kortex_driver::GetGPIOStateRequest> should match
// service_traits::DataType< ::kortex_driver::GetGPIOState >
template<>
struct DataType< ::kortex_driver::GetGPIOStateRequest>
{
  static const char* value()
  {
    return DataType< ::kortex_driver::GetGPIOState >::value();
  }
  static const char* value(const ::kortex_driver::GetGPIOStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kortex_driver::GetGPIOStateResponse> should match
// service_traits::MD5Sum< ::kortex_driver::GetGPIOState >
template<>
struct MD5Sum< ::kortex_driver::GetGPIOStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kortex_driver::GetGPIOState >::value();
  }
  static const char* value(const ::kortex_driver::GetGPIOStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kortex_driver::GetGPIOStateResponse> should match
// service_traits::DataType< ::kortex_driver::GetGPIOState >
template<>
struct DataType< ::kortex_driver::GetGPIOStateResponse>
{
  static const char* value()
  {
    return DataType< ::kortex_driver::GetGPIOState >::value();
  }
  static const char* value(const ::kortex_driver::GetGPIOStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_GETGPIOSTATE_H
