// Generated by gencpp from file kortex_driver/GetTwistSoftLimitationResponse.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_GETTWISTSOFTLIMITATIONRESPONSE_H
#define KORTEX_DRIVER_MESSAGE_GETTWISTSOFTLIMITATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kortex_driver/TwistLimitation.h>

namespace kortex_driver
{
template <class ContainerAllocator>
struct GetTwistSoftLimitationResponse_
{
  typedef GetTwistSoftLimitationResponse_<ContainerAllocator> Type;

  GetTwistSoftLimitationResponse_()
    : output()  {
    }
  GetTwistSoftLimitationResponse_(const ContainerAllocator& _alloc)
    : output(_alloc)  {
  (void)_alloc;
    }



   typedef  ::kortex_driver::TwistLimitation_<ContainerAllocator>  _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetTwistSoftLimitationResponse_

typedef ::kortex_driver::GetTwistSoftLimitationResponse_<std::allocator<void> > GetTwistSoftLimitationResponse;

typedef boost::shared_ptr< ::kortex_driver::GetTwistSoftLimitationResponse > GetTwistSoftLimitationResponsePtr;
typedef boost::shared_ptr< ::kortex_driver::GetTwistSoftLimitationResponse const> GetTwistSoftLimitationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator1> & lhs, const ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator1> & lhs, const ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kortex_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9072bb865353880c3de62e793dbcdb4e";
  }

  static const char* value(const ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9072bb865353880cULL;
  static const uint64_t static_value2 = 0x3de62e793dbcdb4eULL;
};

template<class ContainerAllocator>
struct DataType< ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kortex_driver/GetTwistSoftLimitationResponse";
  }

  static const char* value(const ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TwistLimitation output\n"
"\n"
"================================================================================\n"
"MSG: kortex_driver/TwistLimitation\n"
"\n"
"float32 linear\n"
"float32 angular\n"
;
  }

  static const char* value(const ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTwistSoftLimitationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kortex_driver::GetTwistSoftLimitationResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    s << std::endl;
    Printer< ::kortex_driver::TwistLimitation_<ContainerAllocator> >::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_GETTWISTSOFTLIMITATIONRESPONSE_H
