// Generated by gencpp from file kortex_driver/IntrinsicProfileIdentifier.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_INTRINSICPROFILEIDENTIFIER_H
#define KORTEX_DRIVER_MESSAGE_INTRINSICPROFILEIDENTIFIER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kortex_driver
{
template <class ContainerAllocator>
struct IntrinsicProfileIdentifier_
{
  typedef IntrinsicProfileIdentifier_<ContainerAllocator> Type;

  IntrinsicProfileIdentifier_()
    : sensor(0)
    , resolution(0)  {
    }
  IntrinsicProfileIdentifier_(const ContainerAllocator& _alloc)
    : sensor(0)
    , resolution(0)  {
  (void)_alloc;
    }



   typedef uint32_t _sensor_type;
  _sensor_type sensor;

   typedef uint32_t _resolution_type;
  _resolution_type resolution;





  typedef boost::shared_ptr< ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator> const> ConstPtr;

}; // struct IntrinsicProfileIdentifier_

typedef ::kortex_driver::IntrinsicProfileIdentifier_<std::allocator<void> > IntrinsicProfileIdentifier;

typedef boost::shared_ptr< ::kortex_driver::IntrinsicProfileIdentifier > IntrinsicProfileIdentifierPtr;
typedef boost::shared_ptr< ::kortex_driver::IntrinsicProfileIdentifier const> IntrinsicProfileIdentifierConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator1> & lhs, const ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator2> & rhs)
{
  return lhs.sensor == rhs.sensor &&
    lhs.resolution == rhs.resolution;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator1> & lhs, const ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kortex_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2934edac4ee0b8f88644bc2d0135508a";
  }

  static const char* value(const ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2934edac4ee0b8f8ULL;
  static const uint64_t static_value2 = 0x8644bc2d0135508aULL;
};

template<class ContainerAllocator>
struct DataType< ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kortex_driver/IntrinsicProfileIdentifier";
  }

  static const char* value(const ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"uint32 sensor\n"
"uint32 resolution\n"
;
  }

  static const char* value(const ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sensor);
      stream.next(m.resolution);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IntrinsicProfileIdentifier_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kortex_driver::IntrinsicProfileIdentifier_<ContainerAllocator>& v)
  {
    s << indent << "sensor: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.sensor);
    s << indent << "resolution: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.resolution);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_INTRINSICPROFILEIDENTIFIER_H
