// Generated by gencpp from file kortex_driver/OnNotificationRobotEventTopic.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_ONNOTIFICATIONROBOTEVENTTOPIC_H
#define KORTEX_DRIVER_MESSAGE_ONNOTIFICATIONROBOTEVENTTOPIC_H

#include <ros/service_traits.h>


#include <kortex_driver/OnNotificationRobotEventTopicRequest.h>
#include <kortex_driver/OnNotificationRobotEventTopicResponse.h>


namespace kortex_driver
{

struct OnNotificationRobotEventTopic
{

typedef OnNotificationRobotEventTopicRequest Request;
typedef OnNotificationRobotEventTopicResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OnNotificationRobotEventTopic
} // namespace kortex_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kortex_driver::OnNotificationRobotEventTopic > {
  static const char* value()
  {
    return "6fefdd07c6cb63a94f7b48e7e07e815b";
  }

  static const char* value(const ::kortex_driver::OnNotificationRobotEventTopic&) { return value(); }
};

template<>
struct DataType< ::kortex_driver::OnNotificationRobotEventTopic > {
  static const char* value()
  {
    return "kortex_driver/OnNotificationRobotEventTopic";
  }

  static const char* value(const ::kortex_driver::OnNotificationRobotEventTopic&) { return value(); }
};


// service_traits::MD5Sum< ::kortex_driver::OnNotificationRobotEventTopicRequest> should match
// service_traits::MD5Sum< ::kortex_driver::OnNotificationRobotEventTopic >
template<>
struct MD5Sum< ::kortex_driver::OnNotificationRobotEventTopicRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kortex_driver::OnNotificationRobotEventTopic >::value();
  }
  static const char* value(const ::kortex_driver::OnNotificationRobotEventTopicRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kortex_driver::OnNotificationRobotEventTopicRequest> should match
// service_traits::DataType< ::kortex_driver::OnNotificationRobotEventTopic >
template<>
struct DataType< ::kortex_driver::OnNotificationRobotEventTopicRequest>
{
  static const char* value()
  {
    return DataType< ::kortex_driver::OnNotificationRobotEventTopic >::value();
  }
  static const char* value(const ::kortex_driver::OnNotificationRobotEventTopicRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kortex_driver::OnNotificationRobotEventTopicResponse> should match
// service_traits::MD5Sum< ::kortex_driver::OnNotificationRobotEventTopic >
template<>
struct MD5Sum< ::kortex_driver::OnNotificationRobotEventTopicResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kortex_driver::OnNotificationRobotEventTopic >::value();
  }
  static const char* value(const ::kortex_driver::OnNotificationRobotEventTopicResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kortex_driver::OnNotificationRobotEventTopicResponse> should match
// service_traits::DataType< ::kortex_driver::OnNotificationRobotEventTopic >
template<>
struct DataType< ::kortex_driver::OnNotificationRobotEventTopicResponse>
{
  static const char* value()
  {
    return DataType< ::kortex_driver::OnNotificationRobotEventTopic >::value();
  }
  static const char* value(const ::kortex_driver::OnNotificationRobotEventTopicResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_ONNOTIFICATIONROBOTEVENTTOPIC_H
