// Generated by gencpp from file kortex_driver/PlayAdvancedSequenceRequest.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_PLAYADVANCEDSEQUENCEREQUEST_H
#define KORTEX_DRIVER_MESSAGE_PLAYADVANCEDSEQUENCEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kortex_driver/AdvancedSequenceHandle.h>

namespace kortex_driver
{
template <class ContainerAllocator>
struct PlayAdvancedSequenceRequest_
{
  typedef PlayAdvancedSequenceRequest_<ContainerAllocator> Type;

  PlayAdvancedSequenceRequest_()
    : input()  {
    }
  PlayAdvancedSequenceRequest_(const ContainerAllocator& _alloc)
    : input(_alloc)  {
  (void)_alloc;
    }



   typedef  ::kortex_driver::AdvancedSequenceHandle_<ContainerAllocator>  _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlayAdvancedSequenceRequest_

typedef ::kortex_driver::PlayAdvancedSequenceRequest_<std::allocator<void> > PlayAdvancedSequenceRequest;

typedef boost::shared_ptr< ::kortex_driver::PlayAdvancedSequenceRequest > PlayAdvancedSequenceRequestPtr;
typedef boost::shared_ptr< ::kortex_driver::PlayAdvancedSequenceRequest const> PlayAdvancedSequenceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator1> & lhs, const ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input == rhs.input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator1> & lhs, const ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kortex_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68eaed03acf6865449c7e34f1fcb190e";
  }

  static const char* value(const ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68eaed03acf68654ULL;
  static const uint64_t static_value2 = 0x49c7e34f1fcb190eULL;
};

template<class ContainerAllocator>
struct DataType< ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kortex_driver/PlayAdvancedSequenceRequest";
  }

  static const char* value(const ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "AdvancedSequenceHandle input\n"
"\n"
"================================================================================\n"
"MSG: kortex_driver/AdvancedSequenceHandle\n"
"\n"
"SequenceHandle handle\n"
"bool in_loop\n"
"================================================================================\n"
"MSG: kortex_driver/SequenceHandle\n"
"\n"
"uint32 identifier\n"
"uint32 permission\n"
;
  }

  static const char* value(const ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlayAdvancedSequenceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kortex_driver::PlayAdvancedSequenceRequest_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    s << std::endl;
    Printer< ::kortex_driver::AdvancedSequenceHandle_<ContainerAllocator> >::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_PLAYADVANCEDSEQUENCEREQUEST_H
