// Generated by gencpp from file kortex_driver/StopTeaching.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_STOPTEACHING_H
#define KORTEX_DRIVER_MESSAGE_STOPTEACHING_H

#include <ros/service_traits.h>


#include <kortex_driver/StopTeachingRequest.h>
#include <kortex_driver/StopTeachingResponse.h>


namespace kortex_driver
{

struct StopTeaching
{

typedef StopTeachingRequest Request;
typedef StopTeachingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopTeaching
} // namespace kortex_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kortex_driver::StopTeaching > {
  static const char* value()
  {
    return "f335b819dc59099fe3124b36f140ad07";
  }

  static const char* value(const ::kortex_driver::StopTeaching&) { return value(); }
};

template<>
struct DataType< ::kortex_driver::StopTeaching > {
  static const char* value()
  {
    return "kortex_driver/StopTeaching";
  }

  static const char* value(const ::kortex_driver::StopTeaching&) { return value(); }
};


// service_traits::MD5Sum< ::kortex_driver::StopTeachingRequest> should match
// service_traits::MD5Sum< ::kortex_driver::StopTeaching >
template<>
struct MD5Sum< ::kortex_driver::StopTeachingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kortex_driver::StopTeaching >::value();
  }
  static const char* value(const ::kortex_driver::StopTeachingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kortex_driver::StopTeachingRequest> should match
// service_traits::DataType< ::kortex_driver::StopTeaching >
template<>
struct DataType< ::kortex_driver::StopTeachingRequest>
{
  static const char* value()
  {
    return DataType< ::kortex_driver::StopTeaching >::value();
  }
  static const char* value(const ::kortex_driver::StopTeachingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kortex_driver::StopTeachingResponse> should match
// service_traits::MD5Sum< ::kortex_driver::StopTeaching >
template<>
struct MD5Sum< ::kortex_driver::StopTeachingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kortex_driver::StopTeaching >::value();
  }
  static const char* value(const ::kortex_driver::StopTeachingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kortex_driver::StopTeachingResponse> should match
// service_traits::DataType< ::kortex_driver::StopTeaching >
template<>
struct DataType< ::kortex_driver::StopTeachingResponse>
{
  static const char* value()
  {
    return DataType< ::kortex_driver::StopTeaching >::value();
  }
  static const char* value(const ::kortex_driver::StopTeachingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_STOPTEACHING_H
