# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kortex_driver/ConstrainedPose.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import kortex_driver.msg

class ConstrainedPose(genpy.Message):
  _md5sum = "201b7431451c1b450ae81fca8778070f"
  _type = "kortex_driver/ConstrainedPose"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
Pose target_pose
CartesianTrajectoryConstraint constraint
================================================================================
MSG: kortex_driver/Pose

float32 x
float32 y
float32 z
float32 theta_x
float32 theta_y
float32 theta_z
================================================================================
MSG: kortex_driver/CartesianTrajectoryConstraint

CartesianTrajectoryConstraint_type oneof_type
================================================================================
MSG: kortex_driver/CartesianTrajectoryConstraint_type

CartesianSpeed[] speed
uint32[] duration
================================================================================
MSG: kortex_driver/CartesianSpeed

float32 translation
float32 orientation"""
  __slots__ = ['target_pose','constraint']
  _slot_types = ['kortex_driver/Pose','kortex_driver/CartesianTrajectoryConstraint']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       target_pose,constraint

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ConstrainedPose, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.target_pose is None:
        self.target_pose = kortex_driver.msg.Pose()
      if self.constraint is None:
        self.constraint = kortex_driver.msg.CartesianTrajectoryConstraint()
    else:
      self.target_pose = kortex_driver.msg.Pose()
      self.constraint = kortex_driver.msg.CartesianTrajectoryConstraint()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.target_pose.x, _x.target_pose.y, _x.target_pose.z, _x.target_pose.theta_x, _x.target_pose.theta_y, _x.target_pose.theta_z))
      length = len(self.constraint.oneof_type.speed)
      buff.write(_struct_I.pack(length))
      for val1 in self.constraint.oneof_type.speed:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.translation, _x.orientation))
      length = len(self.constraint.oneof_type.duration)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.Struct(pattern).pack(*self.constraint.oneof_type.duration))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.target_pose is None:
        self.target_pose = kortex_driver.msg.Pose()
      if self.constraint is None:
        self.constraint = kortex_driver.msg.CartesianTrajectoryConstraint()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.target_pose.x, _x.target_pose.y, _x.target_pose.z, _x.target_pose.theta_x, _x.target_pose.theta_y, _x.target_pose.theta_z,) = _get_struct_6f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.constraint.oneof_type.speed = []
      for i in range(0, length):
        val1 = kortex_driver.msg.CartesianSpeed()
        _x = val1
        start = end
        end += 8
        (_x.translation, _x.orientation,) = _get_struct_2f().unpack(str[start:end])
        self.constraint.oneof_type.speed.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.constraint.oneof_type.duration = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.target_pose.x, _x.target_pose.y, _x.target_pose.z, _x.target_pose.theta_x, _x.target_pose.theta_y, _x.target_pose.theta_z))
      length = len(self.constraint.oneof_type.speed)
      buff.write(_struct_I.pack(length))
      for val1 in self.constraint.oneof_type.speed:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.translation, _x.orientation))
      length = len(self.constraint.oneof_type.duration)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.constraint.oneof_type.duration.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.target_pose is None:
        self.target_pose = kortex_driver.msg.Pose()
      if self.constraint is None:
        self.constraint = kortex_driver.msg.CartesianTrajectoryConstraint()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.target_pose.x, _x.target_pose.y, _x.target_pose.z, _x.target_pose.theta_x, _x.target_pose.theta_y, _x.target_pose.theta_z,) = _get_struct_6f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.constraint.oneof_type.speed = []
      for i in range(0, length):
        val1 = kortex_driver.msg.CartesianSpeed()
        _x = val1
        start = end
        end += 8
        (_x.translation, _x.orientation,) = _get_struct_2f().unpack(str[start:end])
        self.constraint.oneof_type.speed.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.constraint.oneof_type.duration = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
