# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kortex_driver/KinematicLimitsList.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import kortex_driver.msg

class KinematicLimitsList(genpy.Message):
  _md5sum = "85620e63d1ea4e2fbf21a5cb16cb2964"
  _type = "kortex_driver/KinematicLimitsList"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
KinematicLimits[] kinematic_limits_list
================================================================================
MSG: kortex_driver/KinematicLimits

uint32 control_mode
float32 twist_linear
float32 twist_angular
float32[] joint_speed_limits
float32[] joint_acceleration_limits"""
  __slots__ = ['kinematic_limits_list']
  _slot_types = ['kortex_driver/KinematicLimits[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       kinematic_limits_list

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(KinematicLimitsList, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.kinematic_limits_list is None:
        self.kinematic_limits_list = []
    else:
      self.kinematic_limits_list = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.kinematic_limits_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.kinematic_limits_list:
        _x = val1
        buff.write(_get_struct_I2f().pack(_x.control_mode, _x.twist_linear, _x.twist_angular))
        length = len(val1.joint_speed_limits)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(struct.Struct(pattern).pack(*val1.joint_speed_limits))
        length = len(val1.joint_acceleration_limits)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(struct.Struct(pattern).pack(*val1.joint_acceleration_limits))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.kinematic_limits_list is None:
        self.kinematic_limits_list = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.kinematic_limits_list = []
      for i in range(0, length):
        val1 = kortex_driver.msg.KinematicLimits()
        _x = val1
        start = end
        end += 12
        (_x.control_mode, _x.twist_linear, _x.twist_angular,) = _get_struct_I2f().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.joint_speed_limits = s.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.joint_acceleration_limits = s.unpack(str[start:end])
        self.kinematic_limits_list.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.kinematic_limits_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.kinematic_limits_list:
        _x = val1
        buff.write(_get_struct_I2f().pack(_x.control_mode, _x.twist_linear, _x.twist_angular))
        length = len(val1.joint_speed_limits)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(val1.joint_speed_limits.tostring())
        length = len(val1.joint_acceleration_limits)
        buff.write(_struct_I.pack(length))
        pattern = '<%sf'%length
        buff.write(val1.joint_acceleration_limits.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.kinematic_limits_list is None:
        self.kinematic_limits_list = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.kinematic_limits_list = []
      for i in range(0, length):
        val1 = kortex_driver.msg.KinematicLimits()
        _x = val1
        start = end
        end += 12
        (_x.control_mode, _x.twist_linear, _x.twist_angular,) = _get_struct_I2f().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.joint_speed_limits = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sf'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.joint_acceleration_limits = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
        self.kinematic_limits_list.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_I2f = None
def _get_struct_I2f():
    global _struct_I2f
    if _struct_I2f is None:
        _struct_I2f = struct.Struct("<I2f")
    return _struct_I2f
