# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kortex_driver/TransformationMatrix.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import kortex_driver.msg

class TransformationMatrix(genpy.Message):
  _md5sum = "01b579348ba31feab01058d980795bad"
  _type = "kortex_driver/TransformationMatrix"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
TransformationRow r0
TransformationRow r1
TransformationRow r2
TransformationRow r3
================================================================================
MSG: kortex_driver/TransformationRow

float32 c0
float32 c1
float32 c2
float32 c3"""
  __slots__ = ['r0','r1','r2','r3']
  _slot_types = ['kortex_driver/TransformationRow','kortex_driver/TransformationRow','kortex_driver/TransformationRow','kortex_driver/TransformationRow']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       r0,r1,r2,r3

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TransformationMatrix, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.r0 is None:
        self.r0 = kortex_driver.msg.TransformationRow()
      if self.r1 is None:
        self.r1 = kortex_driver.msg.TransformationRow()
      if self.r2 is None:
        self.r2 = kortex_driver.msg.TransformationRow()
      if self.r3 is None:
        self.r3 = kortex_driver.msg.TransformationRow()
    else:
      self.r0 = kortex_driver.msg.TransformationRow()
      self.r1 = kortex_driver.msg.TransformationRow()
      self.r2 = kortex_driver.msg.TransformationRow()
      self.r3 = kortex_driver.msg.TransformationRow()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_16f().pack(_x.r0.c0, _x.r0.c1, _x.r0.c2, _x.r0.c3, _x.r1.c0, _x.r1.c1, _x.r1.c2, _x.r1.c3, _x.r2.c0, _x.r2.c1, _x.r2.c2, _x.r2.c3, _x.r3.c0, _x.r3.c1, _x.r3.c2, _x.r3.c3))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.r0 is None:
        self.r0 = kortex_driver.msg.TransformationRow()
      if self.r1 is None:
        self.r1 = kortex_driver.msg.TransformationRow()
      if self.r2 is None:
        self.r2 = kortex_driver.msg.TransformationRow()
      if self.r3 is None:
        self.r3 = kortex_driver.msg.TransformationRow()
      end = 0
      _x = self
      start = end
      end += 64
      (_x.r0.c0, _x.r0.c1, _x.r0.c2, _x.r0.c3, _x.r1.c0, _x.r1.c1, _x.r1.c2, _x.r1.c3, _x.r2.c0, _x.r2.c1, _x.r2.c2, _x.r2.c3, _x.r3.c0, _x.r3.c1, _x.r3.c2, _x.r3.c3,) = _get_struct_16f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_16f().pack(_x.r0.c0, _x.r0.c1, _x.r0.c2, _x.r0.c3, _x.r1.c0, _x.r1.c1, _x.r1.c2, _x.r1.c3, _x.r2.c0, _x.r2.c1, _x.r2.c2, _x.r2.c3, _x.r3.c0, _x.r3.c1, _x.r3.c2, _x.r3.c3))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.r0 is None:
        self.r0 = kortex_driver.msg.TransformationRow()
      if self.r1 is None:
        self.r1 = kortex_driver.msg.TransformationRow()
      if self.r2 is None:
        self.r2 = kortex_driver.msg.TransformationRow()
      if self.r3 is None:
        self.r3 = kortex_driver.msg.TransformationRow()
      end = 0
      _x = self
      start = end
      end += 64
      (_x.r0.c0, _x.r0.c1, _x.r0.c2, _x.r0.c3, _x.r1.c0, _x.r1.c1, _x.r1.c2, _x.r1.c3, _x.r2.c0, _x.r2.c1, _x.r2.c2, _x.r2.c3, _x.r3.c0, _x.r3.c1, _x.r3.c2, _x.r3.c3,) = _get_struct_16f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_16f = None
def _get_struct_16f():
    global _struct_16f
    if _struct_16f is None:
        _struct_16f = struct.Struct("<16f")
    return _struct_16f
